### ISSUE TITLE
Cannot resolved scope service ... from root provider

### ISSUE THREAD

**Issue by mrodrigues95** [benmccallum/fairybread#43] opened 2021-04-25 00:00 UTC
**Describe the bug**
I receive the following error when performing a mutation with a validator attached.
![image](https://user-images.githubusercontent.com/38141653/115975962-366f9a00-a537-11eb-849d-fa13e3683d3f.png)

Removing `.AddFairyBread()` fixes the error but that's obviously not the desired result.

Hot Chocolate setup:
```
services
    .AddGraphQLServer()
    .AddQueryType()
        .AddTypeExtension<UserQueries>()
        .AddTypeExtension<ClassroomQueries>()
    .AddMutationType()
        .AddTypeExtension<ClassroomMutations>()
        .AddTypeExtension<AuthMutations>()
    .AddType<UserType>()
    .AddType<ClassroomType>()
    .EnableRelaySupport()
    .AddDataLoader<UserByIdDataLoader>()
    .AddDataLoader<ClassroomByIdDataLoader>()
    .AddAuthorization()
    .AddFairyBread();
```

Services:
```
services.AddPooledDbContextFactory<ApplicationDbContext>(opt => {
    opt.UseNpgsql(Configuration.GetConnectionString("DefaultConnection"));
    opt.UseSnakeCaseNamingConvention();
});
services.AddScoped(p =>
    p.GetRequiredService<IDbContextFactory<ApplicationDbContext>>()
        .CreateDbContext());
services.AddValidatorsFromAssemblyContaining<Startup>();
services.AddHotChocolateServices();
services.AddIdentityServices();
```

**Versions:**
 - FairyBread: v6.0.0
 - HotChocolate: v11.1.0
 - FluentValidation: v10.0.4

**Comment by rune-vikestad** [comment] 2021-04-25 09:00
Reproduced in https://github.com/rune-vikestad/fairybread-dependencyinjection-bug

**Comment by benmccallum** [comment] 2021-04-26 12:33
This one is really weird. I don't really understand it, but it seems like the working profile, FluentValidator correctly registers the valiator and you can see it on the ServiceProvider in it's Services property while debugging. But in the non-working profile, it's not there.

**Comment by benmccallum** [comment] 2021-04-26 12:36
What's also strange is that when FairyBread crawls the services at startup to create the cache of validators in your DI, it sees the instance there, as it doesn't throw like it would if there were none.

**Comment by benmccallum** [comment] 2021-04-26 12:43
@JeremySkinner, are you aware of any issues with FluentValidation DI with `"ASPNETCORE_ENVIRONMENT": "Development"`. It's so bizarre there's a difference...

**Comment by JeremySkinner** [comment] 2021-04-26 12:54
@benmccallum so the difference in behaviour is because when the environment is set to `Development`, ASP.NET will validate scoping issues at runtime to ensure that singleton-scoped objects don't depend on request-scoped or transient dependencies. When the environment is set to production, the asp.net service provider doesn't perform this check.

There was an issue that caused this back in 2017 ([see this comment for context](https://github.com/FluentValidation/FluentValidation/issues/474#issuecomment-324088177)), but it shouldn't be an issue with newer versions of asp.net, and we have tests in place to catch this and haven't encountered any failures. 

Looking at the stack trace, it appears that somewhere you have something singleton-scoped that is trying to inject a validator (which is request-scoped as of 10.0).

**Comment by JeremySkinner** [comment] 2021-04-26 13:11
So I think this is the issue:

https://github.com/benmccallum/fairybread/blob/76c39cc4f5ca0b792a37f955636449a255ce12a8/src/FairyBread/IRequestExecutorBuilderExtensions.cs#L21-L22

By registering `DefaultValidatorProvider` as singleton and passing in `sp` as the first argument, you're passing the *root* service provider into the `DefaultValidatorProvider`, rather than the service provider that's for the current http request. When you try and resolve validators inside `GetValidators`, they end up being instantiated by the root service provider, which is causing the error you're seeing (because validators are registered as scoped, but you're resolving them from a non-scoped service provider). 

You'll need to make the `DefaultValidatorProvider` scoped instead, and then I think this should resolve the problem

**Comment by benmccallum** [comment] 2021-04-26 18:16
@JeremySkinner , so glad I tagged you and so very grateful for your help and detailed explanation on this! 

Will look to resolve this tomorrow everyone.

**Comment by benmccallum** [comment] 2021-04-27 09:53
Hi all, I've just pushed a `6.0.1-preview.1` which fixes this. 

There's just one outstanding failing test (which I've currently disabled to get a preview out) which was a test of multiple executions against the `IRequestExecutor`. On the second and third executions, the `IServiceProvider` that `DefaultValidatorProvider` takes as a dependency on is apparently disposed. 

Perhaps this isn't a valid scenario. @michaelstaib, should it be possible to call `ExecuteAsync` on a resolved `IRequestExecutor` multiple times? Any idea what would be disposing the `IServiceProvider`? 

Hmm, perhaps for my tests to be valid now I need to create my own scope that wraps a test... this stuff's tricky :P

**Comment by benmccallum** [comment] 2021-04-27 10:03
I've fixed the test by resolving the executor x times for x executions, each time in a new scope. But not really sure if that's valid. If I hear back from Michael I can wrap this up and do a proper release.

When I get time I'll follow @JeremySkinner 's suggestion about integration testing the different DI behaviour in Development as we've also had issues before with serialization that'd benefit from spitting out JSON via HC's ASP.NET middleware, so I'll take the dive.

**Comment by michaelstaib** [comment] 2021-04-27 10:15
So if you execution on the IRequestExecutor make sure to dispose the results after you have used them. Apart form that you can use it as long as you want .... Except if you are using schema reloads like in schema stitching. In this case we have a proxy class that implements IRequestExecutor which handles all the reload stuff and so on.

**Comment by michaelstaib** [comment] 2021-04-27 10:16
Second, each execution needs a new service scope if you pass in the service provider. If you do not pass in a service provider we will use the main service provider and create a scope internally.

https://github.com/ChilliCream/hotchocolate/blob/79c372debab7ec48a42c616eaa4a58362f18f60b/src/HotChocolate/Core/src/Execution/RequestExecutor.cs#L73

**Comment by rune-vikestad** [comment] 2021-04-27 21:51
Have you tried `6.0.1-preview.1` in https://github.com/rune-vikestad/fairybread-dependencyinjection-bug?

I keep getting this after upgrading;

```json
{
    "errors": [
        {
            "message": "Unexpected Execution Error",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "createFoo"
            ],
            "extensions": {
                "message": "Cannot access a disposed object.\r\nObject name: 'IServiceProvider'.",
                "stackTrace": "   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)\r\n   at FairyBread.DefaultValidatorProvider.GetValidators(IMiddlewareContext context, IInputField argument)+MoveNext()\r\n   at FairyBread.InputValidationMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
            }
        }
    ]
}
```

**Comment by AradAral** [comment] 2021-04-30 19:56
@rune-vikestad I'm encountering the exactly same problem.
Running a mutation a second time causes the following error:

![image](https://user-images.githubusercontent.com/26527405/116747842-c324c700-aa13-11eb-9a0a-d22e7fee6018.png)

**Comment by AradAral** [comment] 2021-05-02 19:46
@benmccallum Any ideas, Ben?

**Comment by benmccallum** [comment] 2021-05-05 09:52
Sorry @rune-vikestad and @AradAral , life's a bit hectic my end at the moment (renovating our place while living in it...). 

I'll try look tonight but if you guys have some time to look too I'd appreciate it.

I would've thought that splitting out the crawling of services into IValidatorRegistry which is singleton, from the IValidatorProvider which is now scoped and gets an IServiceProvider injected, would've resolved this, but I guess for some reason it's passing the same IServiceProvider every time to the IValidatorProvider... so the second time it's used it's disposed...

**Comment by benmccallum** [comment] 2021-05-05 10:13
@AradAral  @rune-vikestad , had a brainwave thinking it through. Why am I injecting IServiceProvider when GetValidators gets `IResolverContext` which carries an `IServiceProvider`. So I made it singleton again and use that now. preview.2 on the way

**Comment by benmccallum** [comment] 2021-05-05 10:21
Confirmed I can run your repro mutation multiple times too @rune-vikestad, and indeed the unit test now correctly imitates that multi-run scenario, so I'm confident this is fixed.

When I get more time I'll add some asp.net core integration tests to spin up a real gql server and implement Jeremy's suggestion to force the DI Development behaviour to get that all checked as well. Raised as #45.

**Closed** 2021-05-11 13:08 UTC
Labels: bug

**Comment by rune-vikestad** [comment] 2021-05-11 19:18
I've tested this today both in my own reproducible, and in our development environment - and everything checks out.

Smooth work @benmccallum - tricky nut this one!

**Comment by benmccallum** [comment] 2021-05-11 21:09
Awesome. Thanks for the confirmation, and for the reproduction!
